### ISSUE TITLE
Since Claude's update, LaTeX rendering are reverted back as soon as we scroll

### ISSUE THREAD

**Issue by gilgaTheDev** [kivvi3412/Claude_Latex_Renderer#1]
When Claude finished writing its answer, we can click on the "Render" button and it effectively produce the LaTex expressions.
But as soon as we scroll down (to see the end of the answer for example): the LaTeX expressions are reverted back to the original. So you need to click again on "Render" to get the LaTeX expression. But then you can't see the beginning of the answer so you scroll up and the LaTex rendering is reverted back...
I understand that this behavior appeared one week ago or so, then it's probably due to some update in Claude.

**Comment by kivvi3412** [comment]
Yes, due to claude's recent update, it automatically restores when he slips at the bottom, so I changed the code a little bit (and updated the repository) so that when the page is at the bottom, it can be rerendered twice without turning back into ugly math.
